FROM java:8-jre
MAINTAINER Cfmoto fangwenfei<1334225082>

ADD ./jar/cfmoto-upms-service-1.3.1.jar /app/


CMD ["java", "-Xmx1000m","-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9230", "-jar", "/app/cfmoto-upms-service-1.3.1.jar"]
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

