FROM java:8-jre
MAINTAINER Cfmoto fangwenfei<1334225082>

ADD ./jar/cfmoto-bar-code-service-1.3.1.jar /app/


CMD ["java", "-Xmx1000m", "-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9209","-jar", "/app/cfmoto-bar-code-service-1.3.1.jar"]
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
EXPOSE 9206
