FROM java:8-jre
MAINTAINER Cfmoto fangwenfei<1334225082>

ADD ./jar/cfmoto-auth-1.3.1.jar /app/


CMD ["java", "-Xmx500m","-jar", "/app/cfmoto-auth-1.3.1.jar"]
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
